# Generated by Django 5.0.6 on 2024-06-09 11:20

import cursapp.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Department name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Department name')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Department name')),
                ('name_ky', models.CharField(max_length=255, null=True, unique=True, verbose_name='Department name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Room number')),
                ('building', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, verbose_name='Room number')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('code', models.SlugField(verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Title')),
                ('title_ky', models.CharField(max_length=255, null=True, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Deadline')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.professor', verbose_name='Professor'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start_time')),
                ('end_time', models.TimeField(verbose_name='Start_time')),
                ('day_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10, verbose_name='Day of Week')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.office', verbose_name='Classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Enrollment date')),
                ('graduation_date', models.DateField(verbose_name='Graduation_date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Enrollment date')),
                ('grade', models.CharField(choices=[('very good', 'Very good'), ('good', 'Good'), ('normally', 'Normally'), ('bad', 'Bad')], verbose_name='Grade')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.student', verbose_name='Student')),
            ],
            bases=(cursapp.models.GradeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PassingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(verbose_name='Submission date')),
                ('grade', models.CharField(choices=[('very good', 'Very good'), ('good', 'Good'), ('normally', 'Normally'), ('bad', 'Bad')], verbose_name='Grade')),
                ('grade_en', models.CharField(choices=[('very good', 'Very good'), ('good', 'Good'), ('normally', 'Normally'), ('bad', 'Bad')], null=True, verbose_name='Grade')),
                ('grade_ru', models.CharField(choices=[('very good', 'Very good'), ('good', 'Good'), ('normally', 'Normally'), ('bad', 'Bad')], null=True, verbose_name='Grade')),
                ('grade_ky', models.CharField(choices=[('very good', 'Very good'), ('good', 'Good'), ('normally', 'Normally'), ('bad', 'Bad')], null=True, verbose_name='Grade')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('feedback_en', models.TextField(null=True, verbose_name='Feedback')),
                ('feedback_ru', models.TextField(null=True, verbose_name='Feedback')),
                ('feedback_ky', models.TextField(null=True, verbose_name='Feedback')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.homework', verbose_name='Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursapp.student', verbose_name='Student')),
            ],
            bases=(cursapp.models.GradeMixin, models.Model),
        ),
    ]
