from .views import (FocultetViewSets, ProfessorViewSets, StudentViewSets, CourseViewSets,
                    OfficeViewSets, ScheduleViewSets, RegistrationcourseViewSets,
                    HomeworkViewSets, PassingexamViewSets)
from django.urls import path

urlpatterns = [
    path('focultet/', FocultetViewSets.as_view({'get': 'list', 'post': 'create'}), name='focultet_list'),

    path('focultet/<int:pk>/', FocultetViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='focultet_detail'),
    path('professor/', ProfessorViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='professor_list'),
    path('professor/<int:pk>/', ProfessorViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='professor_detail'),
    path('student/', StudentViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='student_list'),
    path('student/<int:pk>/', StudentViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='student_detail'),
    path('course/', CourseViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='course_list'),
    path('course/<int:pk>/', CourseViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='course_detail'),
    path('office/', OfficeViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='office_list'),
    path('office/<int:pk>/', OfficeViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='office_detail'),
    path('schedule/', ScheduleViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='schedule_list'),
    path('schedule/<int:pk>/', ScheduleViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='schedule_detail'),
    path('registrationcourse/', RegistrationcourseViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='registrationcourse_list'),
    path('registrationcourse/<int:pk>/',
         RegistrationcourseViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='registrationcourse_detail'),
    path('homework/', HomeworkViewSets.as_view({'get': 'list', 'post': 'create'}),
         name='homework_list'),
    path('homework/<int:pk>/', HomeworkViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='homework_detail'),
    path('passingexam/', PassingexamViewSets.as_view({'get': 'list', 'post': 'create'}), name='passingexam_list'),

    path('passingexam/<int:pk>/',
         PassingexamViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='passingexam_detail'),
]
